import {test} from 'node:test';import assert from 'node:assert/strict';import {randomUUID} from 'node:crypto';
import {fixtures,client} from './fixtures.mjs';import {sql,quote} from '../../tools/db.mjs';
test('real aggregated notifications, reporting, admin authorization, moderation and adjustment ledger',async()=>{
 const f=await fixtures(3);const[a,b,admin]=f.clients;const[ua,ub,um]=f.users;
 const save=(c,args)=>c.rpc('save_discussion',{p_key:randomUUID(),...args});
 try{
  assert.ok((await a.rpc('moderation_queue')).error);assert.ok((await client().rpc('moderation_queue')).error);
  assert.equal((await a.rpc('account_capabilities')).data.is_admin,false);
  assert.equal((await a.auth.updateUser({data:{is_admin:true}})).error,null);assert.equal((await a.rpc('account_capabilities')).data.is_admin,false);
  sql(`update app_private.account_states set is_admin=true where user_id=${quote(um.id)}`);
  const post=await save(a,{p_kind:'post',p_target:null,p_content:'这是一条用于真实管理联调的社区动态。'});assert.equal(post.error,null);const id=post.data;
  for(const c of[b,admin])assert.equal((await c.rpc('set_discussion_like',{p_kind:'post',p_id:id,p_active:true})).error,null);
  assert.equal((await b.rpc('set_discussion_like',{p_kind:'post',p_id:id,p_active:false})).error,null);
  assert.equal((await b.rpc('set_discussion_like',{p_kind:'post',p_id:id,p_active:true})).error,null);
  let notices=(await a.from('notifications').select('*').eq('kind','like')).data;assert.equal(notices.length,1);assert.equal(notices[0].actor_count,2);
  assert.equal((await b.from('notifications').select('*').eq('user_id',ua.id)).data.length,0);
  assert.equal((await b.rpc('mark_notifications_read',{p_ids:[notices[0].id]})).error,null);
  assert.equal((await a.from('notifications').select('read_at').eq('id',notices[0].id).single()).data.read_at,null);
  assert.equal((await a.rpc('mark_notifications_read',{p_ids:[notices[0].id]})).error,null);
  assert.ok((await a.from('notifications').select('read_at').eq('id',notices[0].id).single()).data.read_at);
  const comment=await save(b,{p_kind:'post_comment',p_target:id,p_content:'我在此留下回复，用来核验通知能返回讨论。'});assert.equal(comment.error,null);
  assert.equal((await b.rpc('set_follow',{p_user_id:ua.id,p_following:true})).error,null);
  assert.equal((await a.rpc('daily_checkin')).error,null);
  notices=(await a.from('notifications').select('*')).data;for(const kind of['reply','follow','system'])assert.ok(notices.some(n=>n.kind===kind));
  assert.ok(notices.some(n=>n.href.includes(`#comment-${comment.data}`)));assert.ok(notices.every(n=>!n.title.includes('向你投掷')));
  const report=await b.rpc('submit_report',{p_kind:'community_post',p_id:id,p_reason:'真实联调举报理由，请管理审核。'});assert.equal(report.error,null);
  assert.equal((await b.rpc('submit_report',{p_kind:'community_post',p_id:id,p_reason:'重复举报不应生成第二条记录。'})).data,report.data);
  assert.equal((await a.from('reports').select('*').eq('id',report.data)).data.length,0);
  assert.ok((await a.rpc('moderate',{p_kind:'community_post',p_id:id,p_action:'hidden',p_reason:'越权处理不应成功。'})).error);
  assert.ok((await admin.rpc('moderation_queue')).data.some(r=>r.id===report.data));
  assert.equal((await admin.rpc('moderate',{p_kind:'community_post',p_id:id,p_action:'hidden',p_reason:'联调隐藏内容并记录处理。',p_report:report.data})).error,null);
  assert.equal((await client().from('community_posts').select('*').eq('id',id)).data.length,0);
  assert.equal((await client().from('community_post_comments').select('*').eq('post_id',id)).data.length,0);
  assert.deepEqual((await client().rpc('discussion_thread',{p_kind:'post_comment',p_target:id})).data,[]);
  assert.equal((await b.from('reports').select('status').eq('id',report.data).single()).data.status,'resolved');
  assert.equal((await admin.rpc('moderate',{p_kind:'community_post',p_id:id,p_action:'visible',p_reason:'联调恢复内容，保留审计记录。'})).error,null);
  assert.equal((await client().from('community_posts').select('*').eq('id',id)).data.length,1);
  assert.equal((await admin.rpc('moderate',{p_kind:'profile',p_id:ub.id,p_action:'suspended',p_reason:'联调暂停账号互动权限。'})).error,null);
  assert.ok((await save(b,{p_kind:'post',p_target:null,p_content:'暂停后不能发表这条动态。'})).error);
  assert.equal((await admin.rpc('moderate',{p_kind:'profile',p_id:ub.id,p_action:'normal',p_reason:'联调恢复正常账号权限。'})).error,null);
  const key=randomUUID();const adjustment={p_user:ub.id,p_eggs:4,p_exp:20,p_reason:'联调管理员资产校正记录。',p_key:key};
  assert.ok((await a.rpc('admin_adjust_economy',adjustment)).error);
  const before=(await b.rpc('growth_summary')).data;
  for(let i=0;i<2;i++)assert.equal((await admin.rpc('admin_adjust_economy',adjustment)).error,null);
  assert.ok((await admin.rpc('admin_adjust_economy',{...adjustment,p_eggs:5})).error);
  const after=(await b.rpc('growth_summary')).data;assert.equal(after.wallet.egg_balance,before.wallet.egg_balance+4);assert.equal(after.progress.exp,before.progress.exp+20);
  assert.ok((await admin.rpc('admin_adjust_economy',{...adjustment,p_key:randomUUID(),p_eggs:-10000})).error);
  assert.equal((await b.from('economy_transactions').select('*').eq('idempotency_key',`admin:${key}`)).data.length,2);
  assert.equal((await client().rpc('profile_community',{p_user:ua.id})).data.progress.exp,5);
  console.log('Verified aggregated/private notifications, read isolation, replies/follows/badges, report dedup, hidden-parent RLS, admin denial, suspension, idempotent audited adjustments and nonnegative balance.');
 }finally{sql(`delete from app_private.moderation_audit where admin_id=${quote(um.id)}`);f.cleanup();}
});
